name: Build and deploy to production

on:
  push:
    branches:
      - develop

jobs:
  build-production:
    name: Build staging image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
        
        # Setup doctl
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Build docker image
        run: docker build -f Dockerfile-staging . -t registry.digitalocean.com/prhunter/web:${{github.sha}}
      - name: Push docker image
        run: docker push registry.digitalocean.com/prhunter/web:${{github.sha}}

  deploy-staging:
      name: Deploy web to staging
      runs-on: ubuntu-latest
      needs: build-production
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        # Setup doctl
        - name: Install doctl
          uses: digitalocean/action-doctl@v2
          with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        - run: |-
            doctl kubernetes cluster kubeconfig save prhunter-k8s
        - run: |-
            kubectl --namespace=staging set image deployment/web web=registry.digitalocean.com/prhunter/web:${{github.sha}} --record
            kubectl --namespace=staging rollout status deployment/web
            kubectl --namespace=staging get services -o wide