name: Release to prod

on:
  release:
    types: [published]


jobs:
  build-production:
    name: Build production image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
        # Setup doctl
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Build docker image
        run: docker build -f Dockerfile-prod . -t registry.digitalocean.com/prhunter/web:${{github.ref_name}}
      - name: Push docker image
        run: docker push registry.digitalocean.com/prhunter/web:${{github.ref_name}}

  deploy-production:
      name: Deploy web to production
      runs-on: ubuntu-latest
      needs: build-production
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        # Setup doctl
        - name: Install doctl
          uses: digitalocean/action-doctl@v2
          with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        - run: |-
            doctl kubernetes cluster kubeconfig save prhunter-k8s
        - run: |-
            kubectl --namespace=production set image deployment/web web=registry.digitalocean.com/prhunter/web:${{github.ref_name}}
            kubectl --namespace=production rollout status deployment/web
            kubectl --namespace=production get services -o wide


#TODO:
# - Verify that release was successfull
# - Run sanity tests on prod after release
# - Merge the release to master